<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<?php


?>
<?php if($filter instanceof Magento\CatalogSearch\Model\Layer\Filter\Price ):?>
<?php $range =  $this->getPriceRange($filter);?>
<?php $url = $this->getFilterUrl($filter);?>
<?php //var_dump($url);?>
<script>
var price_url = "<?=$url;?>";
require([
    'jquery',
    "jquery/ui",
    'domReady!'
], function($){
//     `use strict`;
    //console.log("Price Slider..!");
//require(["jquery" , "jquery/jquery-ui"], function($){
    // ...
    $("div#price-slider").slider({
			range: true,
			min: <?=$range['min']?>,
			max: <?=$range['max']?>,
			values: [ <?=$range['min']?>, <?=$range['max']?> ],
			slide: function( event, ui ) {
				$( "#amount-desde" ).val( ui.values[ 0 ] );
				$( "#amount-hasta" ).val( ui.values[ 1 ] );
			},
			change: function( event, ui ) {
                console.log(ui.values[0]+"~"+ui.values[1]);
                if(ui.values[0] == <?=$range['min']?> && ui.values[1] == <?=$range['max']?> ) {
                    $( "#price-filter-query" ).prop('disabled', true);
                } else {
                    $( "#price-filter-query" ).prop('disabled', false);
                }
				//alert(ui.values[0]+"~"+ui.values[1]);
			}
		});
    console.log(<?=$range['min']?>+"~"+<?=$range['max']?>);
	$( "#amount-desde" ).val( $( "#price-slider" ).slider( "values", 0 ) ).keyup(function(){ $( "#price-slider" ).slider( "values", 0, $( "#amount-desde" ).val() ) });
    $( "#amount-hasta" ).val( $( "#price-slider" ).slider( "values", 1 ) ).keyup(function(){ $( "#price-slider" ).slider( "values", 1, $( "#amount-hasta" ).val() ) });
    $( "#price-filter-query" ).click(function() {
        if(price_url.indexOf("?") === -1){
		    window.location.href = price_url+"?price="+$( "#amount-desde" ).val()+"-"+$( "#amount-hasta" ).val();        
        }else{
            //var temp = price_url.split("?");
		    window.location.href = price_url+"&price="+$( "#amount-desde" ).val()+"-"+$( "#amount-hasta" ).val();        
        }
    });
});
</script>
<?php 
?>  
<div id="price-slider"></div>    
<p>
	<span>desde </span><input type="number" id="amount-desde"><span> hasta </span><input type="number" id="amount-hasta">
</p>
<button id="price-filter-query" disabled>FILTRAR</button>

<?php else:?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="my item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
<?php endif;?>
